baseURL = 'https://robne1982.github.io/'
languageCode = 'en-us'
title = 'Panda Poo - The Movies'
theme = "ananke"


DefaultContentLanguage = "en"
SectionPagesMenu = "main"
pagination.pagerSize = 3                  # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[params]
    text_color = ""
    author = ""
    favicon = ""
    site_logo = ""
    description = "The last theme you'll ever need. Maybe."
    # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    background_color_class = "bg-black"
    recent_posts_number = 3
    featured_image_class = "cover bg-center"
    custom_css = ["custom.css"]